### ISSUE TITLE
Path::identical() never worked

### ISSUE THREAD

**Issue by jti-lanl** [pftool/pftool#12]
[Low priority.  See tail of this item.]

Meant to fix this.  The intent is to notice when source and destination are identical (like, same inode on the same FS).  It's called in process_stat_buffer():

```c++
        // Are these items *identical* ? (e.g. same POSIX inode)
        if (p_work->identical(p_dest)) {
            write_count--;
            continue;
        }
```
p_work and p_dest are both just PathPtr.
The Path base-class has this default:

```c++
   virtual bool identical(Path& p)     { return false; } // same item, same FS
   virtual bool identical(PathPtr& p)  { return identical(*p); } // same item, same FS
```
The idea is that subclasses implement e.g. identical(MyType& p), which was supposed to be invoked by the base-class identical(*p).  That doesn't happen.

Luckily, source and destination are never identical, in practice.  If that ever happens, we would fail to detect it.

**Comment by brettkettering** [comment]
It has to do with the C++ methods and their implementation. Jeff thinks he knows what to do to resolve this.

**Comment by jti-lanl** [comment]
Fixed.  Will need further treatment to support sharded MD.

**Comment by jti-lanl** [comment]
Re-opened to be a reminder for MD sharding extensions.

**Comment by jti-lanl** [comment]
Closed.  I'll make a new issue for MD sharding.
