### ISSUE TITLE
Group permission on directories may be incorrect:

### ISSUE THREAD

**Issue by thewacokid** [pftool/pftool#16]
It looks like user groups may not be set properly on output directories, though I believe this did work in the past.

[dbonnie@fta01 ~]$ pfcp -Rn /lustre/scratch/dbonnie/errorlists/ /campaign/admins/dbonnie/
"/users/dbonnie" pfcp -Rn /lustre/scratch/dbonnie/errorlists/ /campaign/admins/dbonnie/
Debugging: dest_path '/campaign/admins/dbonnie' -> dest_node '/campaign/admins/dbonnie/errorlists'
Debugging: Path subclass is 'MARFS_Path'
Debugging: created directory '/campaign/admins/dbonnie/errorlists'
manager: creating temp_path /campaign/admins
INFO  HEADER   ========================  dbonnie564163132016fta04.localdomain  ============================
INFO  HEADER   Starting Path: /lustre/scratch/dbonnie/errorlists
INFO  FOOTER   ========================   NONFATAL ERRORS = 0   ================================
INFO  FOOTER   =================================================================================
INFO  FOOTER   Total Files/Links Examined: 210
INFO  FOOTER   Total Dirs Examined: 1
INFO  FOOTER   Total Buffers Written: 213
INFO  FOOTER   Total Bytes Copied: 4201097366
INFO  FOOTER   Total Megabytes Copied: 4006
INFO  FOOTER   Data Rate: 250 MB/second
INFO  FOOTER   Elapsed Time: 15 seconds
Launched /opt/campaign/pftool/installed/bin/pfcp from host fta04.localdomain at: Thu Mar 31 10:04:56 MDT 2016
Job finished at: Thu Mar 31 10:05:13 MDT 2016
[dbonnie@fta01 ~]$ ls -alh /lustre/scratch/dbonnie/
total 32K
drwxr-xr-x   3 dbonnie dbonnie 4.0K Mar 25 14:24 .
drwxr-xr-x 162 root    root     12K Mar 28 09:08 ..
**drwx------   2 dbonnie dbonnie  20K Mar 25 14:18 errorlists**
[dbonnie@fta01 ~]$ ls -alh /campaign/admins/dbonnie/
total 32K
drwxrwxrwx 3 dbonnie dbonnie 4.0K Mar 31 10:04 .
drwxr-xr-x 9 root    root    4.0K Mar 23 22:30 ..
**drwx------ 2 dbonnie root     16K Mar 31 10:04 errorlists**

**Comment by jti-lanl** [comment]
Fixed.  As discussed, the new approach is to first try to set the destination group to match the source group, and then, if that fails, to set it to the default group of the user.

**Comment by jti-lanl** [comment]
It also appears that the build Dave was testing with might have had both SUID and SGID set, which would explain the creation of group root.  The de-escalation doesn't unset egid.

**Comment by thewacokid** [comment]
The build for pftool does still set the sticky bit for group.  Setting 4755 fixes some of this.
