### ISSUE TITLE
restart on partial-copy is partially-failing on cc-fta

### ISSUE THREAD

**Issue by jti-lanl** [pftool/pftool#20]
Seeing fails doing restart of Multi on the cc-fta test-bed, but not on Hb's cluster.  This is not the same problem as #4.

I think this is what is going on:

CTM is updated once every 4 files, though it may be that more objects are written.  [This applies when using file-mode record-keeping, as opposed to xattrs, and is controlled by the \#define CTF_UPDATE_STORE_LIMIT, in ctf.c.]

Thus, at restart, the first object(s) being rewritten may already exist.  Trying to PUT to an object that already exists gets a 500 from Scality, on cc-fta, but not on Hb's cluster.  Some curl-testing shows that the different Scality versions respond differently to attempts to PUT to a object-path that already exists.  (HEAD of an object returns scality-version "128" on Hb's cluster, "64" on cc-fta.)

**It appears I can fix the problem** by changing CTF_UPDATE_STORE_LIMIT to 0, and rebuilding.  This means the CTM file gets updated after every chunk, which is probably not super-efficient.

**Comment by brettkettering** [comment]
How about starting and looping for up to CTF_UPDATE_STORE_LIMIT times and querying to see if an object exists until you get the answer that it does not exist. Then, update the start position to the first object that does not exist and start copying again.

Brett

**Comment by garygrider** [comment]
Indeed every chunk is not efficient, and if it's from multiple processes, that is really ugly.

Querying objects may not work for some object servers

I thought we settled on a home dir file for status so it worked the same for all copy src/dest, no?

Overwrite of objects entirely seems like it should work on most object servers, but their might be settings for what the obj server does in that case.

Gary

________________________________

**Comment by jti-lanl** [comment]
The updating is all done from a single rank, but I agree that it seems better to avoid updating on every chunk from every worker.  In fact, I was figuring we'd someday make a configuration/run-time parameter to let us further increase the number of chunks to collect before updating, in some cases.

Yes, the CTM updates are done to a file in the homedir.

Scality appears to be forbidding overwrite of an object.  I vaguely remember them confirming this once in the past.  I'll double-check.

Wouldn't GET be expected to either succeed or return 404 Not Found on any object-server?  If so, and we were to try to GET the last expected byte for the potentially-unaccounted objects as Brett suggested, that might be a decent work-around.

Jeff

**Comment by garygrider** [comment]
So how do we know its suspect?  Wouldn't that be all the objects in multi that we don't show as complete in our status?  So 10 objects of the 100,000 make it and we have to check the next 99,990 to see if they are there?  Remember this is very async.

Sounds inefficient.  I suspect get the last byte is likely getting the entire object and giving you the last byte.
If there were the equivalent of a low cost stat, that might work.  Is there such a thing in stupid object land?  Get header info or some such thing?
We only do it on restart of big files, not all the time?

Seems like full object overwrite should work, but maybe only with s3 or some such nonsense?

________________________________

**Comment by jti-lanl** [comment]
You're right; If the first set of chunks to be tried at restart have no necessary relationship to the last set that was to be written before failure, we wouldn't know which of all the CTM-unaccounted chunks might potentially already be written.

We could either:

(a) wait until we get a 500 on any new chunks, check to see whether that one already exists, and, if so, call it good, and update the bitmap accordingly.

(b) Extend CTM to keep track of the set of chunks that are to be written before the next time the bitmap of completed chunks is to be updated.  (In other words, at each bitmap update, we'd also add a list of those chunks that are to be done next.)

(c) We do still update the MarFS chunkInfo in the MD file, on every written chunk.  (This was recently "fixed" to all be done from a single rank, but it is still done.)  We could look at this MarFS chunk-info, compare with the CTM bitmap, and return a list of those chunks that were not accounted in the bitmap.  Or just fix the bitmap.

You might wonder "why do we even bother with maintaining MarFS chunkinfo anymore?"  One thing we're using it for is when someone deletes (unlinks or overwrites) an incomplete N:1 file.  GC needs to be able to find those objects that were written.  It's possible we'll have other ways to find such objects, in some cases.   The MarFS chunk-info MD could also potentially allow restarting a write to a Multi via marfs_pipe (i.e. ignore all the input until you get to the offset where you last wrote).   Maybe other uses, as well?

Thanks,
Jeff

**Comment by garygrider** [comment]
If the obj server can't just overwrite
And
If the obj server doesn't have a stat like call

Then option a seems best
If we are in restart of a big file, if our bitmap says we haven't sent it yet - which I assume is a decision made by the mother when assigning work, if we get a 500, then we check the last byte or length, if it checks out we tell the follower proc we sent it ( even though we didn't), the follower proc batches and updates the bitmask file.  If the last byte/size seems wrong, we throw a fatal, if we don't get the 500 we send the object as normal
We do all this only in restart of big file, or any time we get a 500 ?  It really shouldn't happen except in restart of big multi part file.

I think Marfs chunk info is really for reclaim and fuse, no?

Obj Overwrite is still preferred.

The only things this should happen on is objects that got written and it died before updating the bitmask file.  This is possible even if you update the bitmask file every chunk because of natural async race, so depending on that is inefficient and really doesn't solve the problem because it's not really atomic no matter what you do.

Sound right?

________________________________

**Comment by brettkettering** [comment]
I agree under the conditions stated that (a) would be best. An alternative to (a) would be to delete that object and rewrite it. But, if we’re confident that if the object exists that it is complete and correct, then simply mark it as copied and move-on.

Brett

**Comment by jti-lanl** [comment]
It appears that delete and rewrite is also prohibited, on newer Scality versions, according to a quick test.  Waiting for confirmation.

Thanks,
Jeff

**Comment by jti-lanl** [comment]
Sounds good.  Working on it.

I'd guess any obj-server would have a stat-like call (e.g. HEAD), but I'd also guess it's kind of expensive to do on every chunk, after an N:1 restart, given that we don't know which chunks were about to get written before the interruption.  (Our poor underpowered cc-fta cluster takes ~20 sec to respond to a HEAD req.)

Your suggested implementation of option (a) is the same as what I pictured, and it's only for N:1 restart.  (Given that the source and destination have already passed a metadata comparison, maybe it's good enough for us to assure that the obj-length matches expectations.)

Getting a 500 when we're not restarting a Multi ought to be a failure.

Thanks,
Jeff

**Comment by garygrider** [comment]
Might be configurable, but likely it's eventually consistent anyway

I think overwrite versioned objects is more likely supported or configurable

But if not we have a way below

________________________________

**Comment by jti-lanl** [comment]
Fixed.  On these failed writes, we check to see whether the destination-chunk already exists, and matches the size of the data we were going to write to it.  If so, we deem it a success.

Pftool prints a "*" before such deemed successes, so you can at least see that they are happening.

> RANK   3: INFO  DATACOPY *Copied /src/f1 offs 0 len 1073738881 to /dst/f1
> RANK   3: INFO  DATACOPY *Copied /src/f1 offs 1073738881 len 1073738881 to /dst/f1
> RANK   3: INFO  DATACOPY Copied /src/f1 offs 2147477762 len 1073738881 to /dst/f1
> RANK   3: INFO  DATACOPY Copied /src/f1 offs 3221216643 len 1073738881 to /dst/f1
