### ISSUE TITLE
Make pfcp do permissions & ownership like cp

### ISSUE THREAD

**Issue by brettkettering** [pftool/pftool#24]
Update pfcp's permission and ownership handling functionality for applying permissions and ownership as cp does. Add cp's -p flag capability for preserving source permission and ownership on destination.

**Comment by jti-lanl** [comment]
[from the commit-log:]

Fixed the default behavior to always attempt to chmod the destination to match the source.  This is POSIX copy behavior.

For the root-user, or if the new '-o' cmd-line flag is specified ('-p' was already taken), we also try to chown the destination to match the user/group of the source.

Failures are considered non-fatal, but they do get reported.
    
TBD: libmarfs doesn't yet handle umask.


[Here](https://github.com/pftool/pftool/files/279702/jti.txt) is an example of a user copying files having varied permissions and ownership, with and without the '-o' flag:
