### ISSUE TITLE
pfcm failures don't set $?

### ISSUE THREAD

**Issue by gregorygeller** [pftool/pftool#29]
Just noticed that running pfcm -M on two different files doesn't result in setting $? to non-zero even though it results in a nonfatal error.

It makes sense to me that any error (fatal or otherwise) should set $?.

Thoughts?

**Comment by cadejager** [comment]
At the same time that I fixed the pfcp not setting $? I also set pfcm and pfls to do the same. I have not tested them in this specific case. I will try running pftool directly for a compare and see what it does.

**Comment by garygrider** [comment]
Cool, thanks

**Comment by cadejager** [comment]
So I ran pftool directly using the following command:
mpirun -np 4 ./pftool -w 2 -p ./pfcp -c ./pfcm

It returns 0 for status. It if fine to consider this a bug but I would like to defer fixing it until we finish other things for secure campaign.

**Comment by gsparrow** [comment]
It does not return an error code when the files mismatch (but does tell you that they mismatch)
It does not return an error code when you pass pftool two source directories and no destination directory.

It does return an error code when you pass pftool two destination directories and no source directory.

**Comment by gsparrow** [comment]
- PFTool does not return an error code when passed a valid -p option and no -c option.
- PFTool does not return an error code when passed a valid -p in POSIX and a Non-Existent File as -c in MarFS
- PFTool does not return an error code when passed a valid -p in MarFS and a Non-Existent File as -c in POSIX

**Comment by cadejager** [comment]
Pftool now returns nonzero status codes if there are non fatal errors as of commit c173aaf9411fe015f9c8e80a983d3d695940dc9d I believe this may also fix this issue but testing will show if this catches all cases.
