### ISSUE TITLE
Pftool uses a regular lstat in file copies were multiple inputs are provided

### ISSUE THREAD

**Issue by cadejager** [pftool/pftool#3]
This causes problems if it is copying to a file system like marfs and the fuse mount is not available.

The cause of the problem is in src/pftool.cpp.
Search for "Multiple inputs and target '%s' is not a directory\n"

Reproduce with:
mpirun -n 4 /home/dejager/pftool/installed/bin/../bin/pftool -w 0 -r -c /marfs/dejager/test/ -p /home/dejager/test/

**Comment by jti-lanl** [comment]
It was just as you said.  Thanks for finding and reporting bugs.  The fix is just to replace the "lstat(…)" with some of our new-fangled C++ goodness.  Done.

**Comment by dsherril** [comment]
Jeff,

Just a minor point - in my experience, the term "bug" implies something 
that does not work or is the wrong logic in a piece of code. Prior to 
the creation of the new Marfs requirements placed on PFTOOL, the use of 
lstat() was perfectly OK. Perhaps it would be better to say "finding 
additional places to change, so that PFTOOL works with the new 
requirements...".

David

**Comment by jti-lanl** [comment]
Good point, David.

I agree with you.  I think what happens is that users of the new code (in the 'cpp' branch) will just see bad behavior as a "bug" in pftool, which it is, though in many cases it is really a bug in my implementation of extensions/replacements, on top of old pftool.

I am concerned about any bugs I may have introduced into legacy behavior, if/when we merge the new branch into the master.  I have left large swaths of the old code commented out, next to the replacements in the new idiom, in hopes that it may help you/me/us find such bugs in the future.  The point of leaving the comments in is to help you and me to make the transition as smoothly as possible. 

I appreciate your patience with having the ground changed under your feet, and I'm hoping you'll eventually look at the new approach and agree that it makes the whole thing more legible and flexible, at the cost of some transitional bugs, like this one, and some abstraction.  (Just imagine the additional contortions of #ifdefs that would have been required to add build-time options for non-POSIX protocols like S3/MarFS, without the new approach.  That was the motivation for the new approach.)


Thanks,
Jeff
