### ISSUE TITLE
core files are created when copy is called with a non existiant source

### ISSUE THREAD

**Issue by cadejager** [pftool/pftool#32]

**Comment by cadejager** [comment]
MPI appears to dump core files when MPI_ABORT is called. I wrote a test program to test this. Unless there is a way to change this I think we will need to live with the core files and I do not want to add the logic to pftool to avoid MPI_ABORT.

**Comment by jti-lanl** [comment]
I think ‘ulimit -c 0’ will prevent core-files getting dumped.  I had set it to unlimited on one of the VLE FTAs, because there was a crash of fuse, and I wanted to see a core file if I could cause it to happen again.
