### ISSUE TITLE
copy a directory to marfs_mount_point/namespace/ fails

### ISSUE THREAD

**Issue by gsparrow** [pftool/pftool#34]
When copying a directory tree to marfs_mount_point/namespace, pftool is going up a directory to check permissions, this fails as pftool does not have permissions for the marfs mount point, and causes the copy to fail immediately. In directories other than the marfs mount point, this does not cause issue.

`mpirun -np 4 path_to_pftool/pftool -r -w 0 -c /marfs/namespace/ -p /dev/shm/directory_tree`

**Comment by cadejager** [comment]
This was a configuration problem. Batch jobs did not have read permission on the root namespace.

In the root namespace I changed:
<bperms>NONE</bperms>
to
<bperms>RM</bperms>
