### ISSUE TITLE
PFTool fails to list multiple POSIX files

### ISSUE THREAD

**Issue by gsparrow** [pftool/pftool#37]
PFTool fails to list multiple POSIX files, as in the example command
`mpirun -np $NP PFTool -w 1 -p ABSOLUTE_PATH/FILE_0 ABSOLUTE_PATH/FILE_1`
It appears that PFTool gives n-1 non-fatal errors, where n is the number of POSIX files being listed.
In addition, it also cannot list a MarFS file and then a POSIX file, but can list a POSIX file followed by a MarFS file.

**Comment by cadejager** [comment]
This is hopefully fixed by commit 056331b9cf25f79bc2e72e1e56b6f8a0c9b1ef61
