### ISSUE TITLE
PFTool defaults to -w 1 when not given a -w arguement

### ISSUE THREAD

**Issue by gsparrow** [pftool/pftool#39]
When running PFTool with no -w arguement, it appears to default to -w 1 or listing the files.
`mpirun -np $NP PFTool -p ABSOLUTE_PATH/FILE_0 -c ABSOLUTE_PATH/FILE_1`
It works this way regardless of MarFS or POSIX, and regardless of whether or not you include the -c arguement.

**Comment by cadejager** [comment]
This is the way pftool is written, to default to ls. I will reopen this issue if people don't think this should be the default behavior.
