### ISSUE TITLE
pfscripts.py assumes pftool location

### ISSUE THREAD

**Issue by gsparrow** [pftool/pftool#44]
In pfscripts.py, on line 11, it assumes pftool is located in the ../bin/ directory. The default behaviour should be to check for an environment variable, and failing an environment variable, check the PATH variable.

The script also assumes the location of pftool.cfg is in ../etc/

**Comment by cadejager** [comment]
@dsherril George fixed this but also added pfscripts.py to look in PATH for pftool. He made this a higher priority than looking in ../bin/.

I changed this to not look in path but we needed the environment variable for testing. I think that we should look in the environment, then in ../bin, and finally look in path. What is your preference?

**Comment by cadejager** [comment]
I spoke to Jeff and he agreed that we did not need to check the path.
