### ISSUE TITLE
Change the Default chunksize and chunk_at to 10GB

### ISSUE THREAD

**Issue by cadejager** [pftool/pftool#59]
Currently the default pftool chunksize and chunk_at is set to 100GB. In the pfscripts it defaults to 10GB. I would like to change both of these defaults to 10GB as it has caused some confusion in our testing with the chunk_at so large.

The change would affect pftool.cpp:177-178. Is this an acceptable change?

**Comment by jti-lanl** [comment]
I think all users (at LANL) should be going through pfcp/pfcm, so this wouldn’t change anything for them, and would save testers from having to learn the hard way.

For MarFS, when testing pftool by hand, I’ve gotten in the habit of using ‘-C 1’, which effectively means “go ask the filesystem what chunksize to use, for a file of this size, and then chunk-at that”.  In other words, this just boils down to using whatever MarFS thinks the chunk-size should be.  For other filesystems, it will set chunk_at to whatever the provided or default chunk-size is.
