### ISSUE TITLE
Is <xfs/xfs.h> nessarry in ctm.h?

### ISSUE THREAD

**Issue by cadejager** [pftool/pftool#64]
@dsherril I have been trying to get pftool to build on REHL 7. Apperatnly BITS_PER_LONG is no longer defined in xfs.h. In commit f6d31e31053be67d2992be020b4388b0715b4e45 I finished defining it myself by doing the following:
```c
#ifndef BITS_PER_LONG
#define BITS_PER_LONG (sizeof(long)*8)
#endif /* BITS_PER_LONG */
```
I am still dependent on xfs.h for ENOATTR which is used somewhere but we could define an error for that ourselves as well and I think it would be nice to not be dependent on xfs-devel.

1. Do you see anything wrong with defining BITS_PER_LONG this way?
2. Is it reasonable to manually define ENOATTR (or a non conflicting name) and completely remove our dependency on xfs.h?

**Comment by thewacokid** [comment]
I will cast my vote for removing the dependency on xfs-devel, since it has caused pain in the past on other systems too. :)

**Comment by brettkettering** [comment]
It looks like it was moved to uapi/asm/bitsperlong.h

Brett

**Comment by jti-lanl** [comment]
I haven’t done a careful search regarding portability, but apparently ENOATTR is a synonym for ENODATA, which is defined in attr/xattr.h.

**Comment by cadejager** [comment]
This dependency has been removed in the rehl7_support branch.
