### ISSUE TITLE
Pftool will not build

### ISSUE THREAD

**Issue by smngalexa** [pftool/pftool#77]
Pftool will not build.

Centos - 6.7 

> make
make  all-recursive
make[1]: Entering directory `/users/alexa/src/pftool'
Making all in src
make[2]: Entering directory `/users/alexa/src/pftool/src'
  CC     __top_builddir__bin_pftool-cta.o
  CC     __top_builddir__bin_pftool-ctf.o
  CC     __top_builddir__bin_pftool-ctm.o
  CC     __top_builddir__bin_pftool-hashtbl.o
  CC     __top_builddir__bin_pftool-hashdataCTM.o
  CC     __top_builddir__bin_pftool-str.o
  CXX    __top_builddir__bin_pftool-pfutils.o
pfutils.cpp: In function ‘void pack_list(path_list*, int, work_buf_list**, work_buf_list**, int*)’:
pfutils.cpp:1587: error: cannot convert ‘int*’ to ‘work_buf_list**’ for argument ‘2’ to ‘void enqueue_buf_list(work_buf_list**, work_buf_list**, int*, char*, int)’
pfutils.cpp: In function ‘int samefile(PathPtr, PathPtr, const options&)’:
pfutils.cpp:1632: error: ‘const struct options’ has no member named ‘preserv’
make[2]: *** [__top_builddir__bin_pftool-pfutils.o] Error 1
make[2]: Leaving directory `/users/alexa/src/pftool/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/users/alexa/src/pftool'
make: *** [all] Error 2

Centos - 7.4

# make
make  all-recursive
make[1]: Entering directory `/root/src/pftool'
Making all in src
make[2]: Entering directory `/root/src/pftool/src'
  CC       __top_builddir__bin_pftool-cta.o
  CC       __top_builddir__bin_pftool-ctf.o
  CC       __top_builddir__bin_pftool-ctm.o
  CC       __top_builddir__bin_pftool-hashtbl.o
  CC       __top_builddir__bin_pftool-hashdataCTM.o
  CC       __top_builddir__bin_pftool-str.o
  CXX      __top_builddir__bin_pftool-pfutils.o
pfutils.cpp: In function ‘void pack_list(path_list*, int, work_buf_list**, work_buf_list**, int*)’:
pfutils.cpp:1587:70: error: cannot convert ‘int*’ to ‘work_buf_list**’ for argument ‘2’ to ‘void enqueue_buf_list(work_buf_list**, work_buf_list**, int*, char*, int)’
        enqueue_buf_list(workbuflist, workbufsize, buffer, buffer_size);
                                                                      ^
pfutils.cpp: In function ‘int samefile(PathPtr, PathPtr, const options&)’:
pfutils.cpp:1632:83: error: ‘const struct options’ has no member named ‘preserv’
  && (((src.st.st_uid == dst.st.st_uid) && (src.st.st_gid == dst.st.st_gid)) || !o.preserv)) {    // only chown if preserve set
                                                                                   ^
make[2]: *** [__top_builddir__bin_pftool-pfutils.o] Error 1
make[2]: Leaving directory `/root/src/pftool/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/src/pftool'
make: *** [all] Error 2

Thanks, Alex

**Comment by jti-lanl** [comment]
notes:

— first error is just that one of the calls to enqueue_buf_list() didn’t get the added argument <workbuftail>.

— second error is that the tweaks in support of adding a new “preserve” command-line flag were not all checked in.




On Apr 5, 2018, at 7:50 AM, smngalexa <notifications@github.com<mailto:notifications@github.com>> wrote:


Pftool will not build.

Centos - 6.7

make
make all-recursive
make[1]: Entering directory /users/alexa/src/pftool' Making all in src make[2]: Entering directory/users/alexa/src/pftool/src'
CC __top_builddir__bin_pftool-cta.o
CC __top_builddir__bin_pftool-ctf.o
CC __top_builddir__bin_pftool-ctm.o
CC __top_builddir__bin_pftool-hashtbl.o
CC __top_builddir__bin_pftool-hashdataCTM.o
CC __top_builddir__bin_pftool-str.o
CXX __top_builddir__bin_pftool-pfutils.o
pfutils.cpp: In function ‘void pack_list(path_list*, int, work_buf_list**, work_buf_list**, int*)’:
pfutils.cpp:1587: error: cannot convert ‘int*’ to ‘work_buf_list**’ for argument ‘2’ to ‘void enqueue_buf_list(work_buf_list**, work_buf_list**, int*, char*, int)’
pfutils.cpp: In function ‘int samefile(PathPtr, PathPtr, const options&)’:
pfutils.cpp:1632: error: ‘const struct options’ has no member named ‘preserv’
make[2]: *** [__top_builddir__bin_pftool-pfutils.o] Error 1
make[2]: Leaving directory /users/alexa/src/pftool/src' make[1]: *** [all-recursive] Error 1 make[1]: Leaving directory/users/alexa/src/pftool'
make: *** [all] Error 2

Centos - 7.4

make

make all-recursive
make[1]: Entering directory /root/src/pftool' Making all in src make[2]: Entering directory/root/src/pftool/src'
CC __top_builddir__bin_pftool-cta.o
CC __top_builddir__bin_pftool-ctf.o
CC __top_builddir__bin_pftool-ctm.o
CC __top_builddir__bin_pftool-hashtbl.o
CC __top_builddir__bin_pftool-hashdataCTM.o
CC __top_builddir__bin_pftool-str.o
CXX __top_builddir__bin_pftool-pfutils.o
pfutils.cpp: In function ‘void pack_list(path_list*, int, work_buf_list**, work_buf_list**, int*)’:
pfutils.cpp:1587:70: error: cannot convert ‘int*’ to ‘work_buf_list**’ for argument ‘2’ to ‘void enqueue_buf_list(work_buf_list**, work_buf_list**, int*, char*, int)’
enqueue_buf_list(workbuflist, workbufsize, buffer, buffer_size);
^
pfutils.cpp: In function ‘int samefile(PathPtr, PathPtr, const options&)’:
pfutils.cpp:1632:83: error: ‘const struct options’ has no member named ‘preserv’
&& (((src.st.st_uid == dst.st.st_uid) && (src.st.st_gid == dst.st.st_gid)) || !o.preserv)) { // only chown if preserve set
^
make[2]: *** [__top_builddir__bin_pftool-pfutils.o] Error 1
make[2]: Leaving directory /root/src/pftool/src' make[1]: *** [all-recursive] Error 1 make[1]: Leaving directory/root/src/pftool'
make: *** [all] Error 2

Thanks, Alex

**Comment by gransom** [comment]
These were introduced by the recent pull request that I merged in.  Must have been miscopied from production.  I've just pushed a commit that seems to fix the build issues.
I plan to go through by hand and make sure there were no other typos made from production.  I'll update again if I find any (though I expect those lines were all of it).

Thanks for drawing attention to this.

**Comment by gransom** [comment]
I haven't spotted any other mistakes.  The master branch build should be fine now.  Closing this issue.
