### ISSUE TITLE
fatal error: openssl/md2.h: No such file or directory

### ISSUE THREAD

**Issue by mxmlnkn** [pftool/pftool#87]
In the first place, the Readme does neither mention that libattr1-dev or libssl-dev have to be installed. I got include errors without these packages, e.g., `xattr.h`.

But libssl-dev also does not seem to work because the version is [too new](https://bugs.launchpad.net/ubuntu/+source/nmap/+bug/785683)? I get:
```
mpic++ -DHAVE_CONFIG_H -I. -I..     -O3     -g  -MT __top_builddir__bin_pftool-cta.o -MD -MP -MF .deps/__top_builddir__bin_pftool-cta.Tpo -c -o __top_builddir__bin_pftool-cta.o `test -f 'cta.c' || echo './'`cta.c
In file included from str.h:9:0,
                 from pfutils.h:39,
                 from cta.c:36:
sig.h:39:27: fatal error: openssl/md2.h: No such file or directory
 #  include <openssl/md2.h>
                           ^
```

**Comment by thewacokid** [comment]
MD2 support is deprecated upstream.  This was an undocumented "feature" in that you have to try to build with DIGEST==MD2 for it to show up.  MD2 support will be removed shortly.
