### ISSUE TITLE
Unable to build pftool without MarFS -

### ISSUE THREAD

**Issue by thewacokid** [pftool/pftool#90]
Looks like there's an assumption in the timing code that MarFS support is being built.  
from pfutils.h:

#ifdef MARFS
#include "erasure.h" /* utils for manipulation of TimingData */
#endif

Except if you're not building with MarFS, this isn't included, and therefore breaks the build since a few types being used are not included.

We either need to require erasureUtils (which I don't think is the best path) or fix this so that it doesn't cause the build to break when not using --enable-marfs.

**Comment by jti-lanl** [comment]
Thanks.  Fixed in 7f25320ed9f54ec
